services:
  # API Service
  - type: web
    name: perago-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://your-api-name.onrender.com
      - key: ORG_DOMAIN
        value: perago.com
      - key: APPROVER_EMAIL
        value: rizu34455@gmail.com
      - key: BACKUP_APPROVER_EMAIL
        value: admin@perago.com

# Database connection will be automatically handled by Render
databases:
  - name: perago-db
    plan: free
